const data1 = [
  {
    PartId: "001",
    UnitWt: "002",
    QtyReceived: "003",
    QtyAccepted: "004",
    QtyRejected: "005",
  },
  {
    PartId: "001",
    UnitWt: "002",
    QtyReceived: "003",
    QtyAccepted: "004",
    QtyRejected: "005",
  },
  {
    PartId: "001",
    UnitWt: "002",
    QtyReceived: "003",
    QtyAccepted: "004",
    QtyRejected: "005",
  },
  {
    PartId: "001",
    UnitWt: "002",
    QtyReceived: "003",
    QtyAccepted: "004",
    QtyRejected: "005",
  },
  {
    PartId: "001",
    UnitWt: "002",
    QtyReceived: "003",
    QtyAccepted: "004",
    QtyRejected: "005",
  },
  {
    PartId: "001",
    UnitWt: "002",
    QtyReceived: "003",
    QtyAccepted: "004",
    QtyRejected: "005",
  },

  {
    PartId: "001",
    UnitWt: "002",
    QtyReceived: "003",
    QtyAccepted: "004",
    QtyRejected: "005",
  },
  {
    PartId: "001",
    UnitWt: "002",
    QtyReceived: "003",
    QtyAccepted: "004",
    QtyRejected: "005",
  },
];

const data2 = [
  {
    select: <input type="checkbox" />,
    RVNo: "002",
    RVdate: "03/12/2022",
    Customer: "004",
    CustDocuNo: "005",
  },
  {
    select: <input type="checkbox" />,
    RVNo: "002",
    RVdate: "03/12/2022",
    Customer: "004",
    CustDocuNo: "005",
  },
  {
    select: <input type="checkbox" />,
    RVNo: "002",
    RVdate: "03/12/2022",
    Customer: "004",
    CustDocuNo: "005",
  },
  {
    select: <input type="checkbox" />,
    RVNo: "002",
    RVdate: "03/12/2022",
    Customer: "004",
    CustDocuNo: "005",
  },
  {
    select: <input type="checkbox" />,
    RVNo: "002",
    RVdate: "03/12/2022",
    Customer: "004",
    CustDocuNo: "005",
  },
  {
    select: <input type="checkbox" />,
    RVNo: "002",
    RVdate: "03/12/2022",
    Customer: "004",
    CustDocuNo: "005",
  },
  {
    select: <input type="checkbox" />,
    RVNo: "002",
    RVdate: "03/12/2022",
    Customer: "004",
    CustDocuNo: "005",
  },
  {
    select: <input type="checkbox" />,
    RVNo: "002",
    RVdate: "03/12/2022",
    Customer: "004",
    CustDocuNo: "005",
  },
  {
    select: <input type="checkbox" />,
    RVNo: "002",
    RVdate: "03/12/2022",
    Customer: "004",
    CustDocuNo: "005",
  },
  {
    select: <input type="checkbox" />,
    RVNo: "002",
    RVdate: "03/12/2022",
    Customer: "004",
    CustDocuNo: "005",
  },
];

const data3 = [
  {
    Srl: "001",
    MtrlCode: "002",
    DynamicF: "100",
    DynamicF: "100",
    DynamicF: "100",
    Qty: "005",
    Inspected: <input type="checkbox" />,
    LocationNo: "111",
    Updated: <input type="checkbox" />,
  },
  {
    Srl: "",
    MtrlCode: "002",
    DynamicF: "100",
    DynamicF: "100",
    DynamicF: "100",
    Qty: "005",
    Inspected: <input type="checkbox" />,
    LocationNo: "111",
    Updated: <input type="checkbox" />,
  },
  {
    Srl: "",
    MtrlCode: "002",
    DynamicF: "100",
    DynamicF: "100",
    DynamicF: "100",
    Qty: "005",
    Inspected: <input type="checkbox" />,
    LocationNo: "111",
    Updated: <input type="checkbox" />,
  },
  {
    Srl: "",
    MtrlCode: "002",
    DynamicF: "100",
    DynamicF: "100",
    DynamicF: "100",
    Qty: "005",
    Inspected: <input type="checkbox" />,
    LocationNo: "111",
    Updated: <input type="checkbox" />,
  },
  {
    Srl: "",
    MtrlCode: "002",
    DynamicF: "100",
    DynamicF: "100",
    DynamicF: "100",
    Qty: "005",
    Inspected: <input type="checkbox" />,
    LocationNo: "111",
    Updated: <input type="checkbox" />,
  },
  {
    Srl: "",
    MtrlCode: "002",
    DynamicF: "100",
    DynamicF: "100",
    DynamicF: "100",
    Qty: "005",
    Inspected: <input type="checkbox" />,
    LocationNo: "111",
    Updated: <input type="checkbox" />,
  },
  {
    Srl: "",
    MtrlCode: "002",
    DynamicF: "100",
    DynamicF: "100",
    DynamicF: "100",
    Qty: "005",
    Inspected: <input type="checkbox" />,
    LocationNo: "111",
    Updated: <input type="checkbox" />,
  },
  {
    Srl: "",
    MtrlCode: "002",
    DynamicF: "100",
    DynamicF: "100",
    DynamicF: "100",
    Qty: "005",
    Inspected: <input type="checkbox" />,
    LocationNo: "111",
    Updated: <input type="checkbox" />,
  },
  {
    Srl: "",
    MtrlCode: "002",
    DynamicF: "100",
    DynamicF: "100",
    DynamicF: "100",
    Qty: "005",
    Inspected: <input type="checkbox" />,
    LocationNo: "111",
    Updated: <input type="checkbox" />,
  },
];

const data5 = [
  {
    Srl: "",
    Description: "asdfghjk",
    Material: "sdfghjkl",
    Qty: "001",
    Weight: "dfgh",
    TotalWeight: "123",
    UpDated: <input type="checkbox" />,
  },
];
const CRVdata1 = [
  {
    RVNo: "",
    CustDocument: "asdfghjk",
    MaterialCode: "sdfghjkl",
    Weight: "dfgh",
    Length: "dfgh",
    Scrap: <input type="checkbox" />,
    Weight: "123",
    ScrapWeight: "1234",
    InStock: "sdfghj",
    Issue: <input type="checkbox" />,
  },
  {
    RVNo: "",
    CustDocument: "asdfghjk",
    MaterialCode: "sdfghjkl",
    Weight: "dfgh",
    Length: "dfgh",
    Scrap: <input type="checkbox" />,
    Weight: "123",
    ScrapWeight: "1234",
    InStock: "sdfghj",
    Issue: <input type="checkbox" />,
  },
  {
    RVNo: "",
    CustDocument: "asdfghjk",
    MaterialCode: "sdfghjkl",
    Weight: "dfgh",
    Length: "dfgh",
    Scrap: <input type="checkbox" />,
    Weight: "123",
    ScrapWeight: "1234",
    InStock: "sdfghj",
    Issue: <input type="checkbox" />,
  },
];
const CRVdata2 = [
  {
    MtrlStockID: "123",
    Issue: <input type="checkbox" />,
    Weight: "123",
    ScrapWeight: "1234",
    RVNo: "",
    UpDated: <input type="checkbox" />,
  },
  {
    MtrlStockID: "123",
    Issue: <input type="checkbox" />,
    Weight: "123",
    ScrapWeight: "1234",
    RVNo: "",
    UpDated: <input type="checkbox" />,
  },
  {
    MtrlStockID: "123",
    Issue: <input type="checkbox" />,
    Weight: "123",
    ScrapWeight: "1234",
    RVNo: "",
    UpDated: <input type="checkbox" />,
  },
];
const CRVdata3 = [
  {
    MtrlStockID: "123",
    MtrlCode: "123",
    DynamicPara1: "sdfghjkl",
    DynamicPara1: "sdfghjkl",
    Weight: "dfgh",
    Scrap: "0",
  },
  {
    MtrlStockID: "123",
    MtrlCode: "123",
    DynamicPara1: "sdfghjkl",
    DynamicPara1: "sdfghjkl",
    Weight: "dfgh",
    Scrap: "0",
  },
  {
    MtrlStockID: "123",
    MtrlCode: "123",
    DynamicPara1: "sdfghjkl",
    DynamicPara1: "sdfghjkl",
    Weight: "dfgh",
    Scrap: "0",
  },
];

const outwarddata = [
  {
    Date: "",
    IVNo: "",
    Customer: "",
    Weight: "",
    Type: "",
  },
];
const returnnewpartdata1 = [
  {
    RVNO: "",
    Select: <input type="checkbox" />,
  },
];

const returnnewpartdata2 = [
  {
    Select: <input type="checkbox" />,
    PartId: "",
    Received: "",
    Rejected: "",
    Issued: "",
    Used: "",
    Returned: "",
  },
];
const returnnewpartdata3 = [
  {
    SlNo: "",
    PartId: "",
    Return: "",
    Remarks: "",
  },
];

export {
  data1,
  data2,
  data3,
  data5,
  CRVdata1,
  CRVdata2,
  CRVdata3,
  outwarddata,
  returnnewpartdata1,
  returnnewpartdata2,
  returnnewpartdata3,
};
